name: Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Environment
        run: |
          echo "Gitea: ${{ gitea.server_url }}"
          echo "Repository: ${{ gitea.repository }}"
          echo "Commit: ${{ gitea.sha }}"
          echo "Hostname: $(hostname)"

      - name: Docker
        run: |
          docker version
          docker info