// <auto-generated />
using Adashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Adashboard.Data.Migrations
{
    [DbContext(typeof(DashboardDbContext))]
    [Migration("20260924174627_AddSiteTitleAndDescription")]
    partial class AddSiteTitleAndDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Adashboard.Models.Dashboard.DashboardCard", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWide")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("DashboardCards", (string)null);
                });

            modelBuilder.Entity("Adashboard.Models.Dashboard.DashboardCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DashboardLayoutId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DashboardLayoutId");

                    b.ToTable("DashboardCategories", (string)null);
                });

            modelBuilder.Entity("Adashboard.Models.Dashboard.DashboardLayout", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("SiteDescription");

                    b.Property<string>("SiteTitle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("SiteTitle");

                    b.Property<string>("ThemeMode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DashboardLayouts", (string)null);
                });

            modelBuilder.Entity("Adashboard.Models.Dashboard.DashboardCard", b =>
                {
                    b.HasOne("Adashboard.Models.Dashboard.DashboardCategory", null)
                        .WithMany("Cards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Adashboard.Models.Dashboard.CardPosition", "Position", b1 =>
                        {
                            b1.Property<int>("DashboardCardId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DisplayOrder");

                            b1.HasKey("DashboardCardId");

                            b1.ToTable("DashboardCards");

                            b1.WithOwner()
                                .HasForeignKey("DashboardCardId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Adashboard.Models.Dashboard.DashboardCategory", b =>
                {
                    b.HasOne("Adashboard.Models.Dashboard.DashboardLayout", null)
                        .WithMany("Categories")
                        .HasForeignKey("DashboardLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Adashboard.Models.Dashboard.CategoryPosition", "Position", b1 =>
                        {
                            b1.Property<int>("DashboardCategoryId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Order")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DisplayOrder");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DisplayWidth");

                            b1.HasKey("DashboardCategoryId");

                            b1.ToTable("DashboardCategories");

                            b1.WithOwner()
                                .HasForeignKey("DashboardCategoryId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Adashboard.Models.Dashboard.DashboardCategory", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Adashboard.Models.Dashboard.DashboardLayout", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
